services:
  # Serviço da aplicação Django
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 project.wsgi:application  # ADICIONE ESTA LINHA
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
    expose:
      - "8000"

  # Serviço do Servidor Web Nginx (Proxy Reverso)
  nginx:
    image: nginx:stable-alpine
    restart: always
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - static_volume:/app/static:ro
      - media_volume:/app/media:ro  # ADICIONE :ro AQUI TAMBÉM
    ports:
      - "80:80"
    depends_on:
      - web

# Volumes persistentes para ficheiros estáticos e uploads
volumes:
  static_volume:
  media_volume: