# Generated by Django 5.0.2 on 2026-02-15 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='_title',
            field=models.CharField(max_length=255),
        ),
    ]
