# Generated by Django 6.0 on 2025-12-24 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post__created_at_post__updated_at_alter_post_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='_status',
            field=models.IntegerField(default=0),
        ),
    ]
