# Generated by Django 6.0 on 2026-02-02 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_visualization_votes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visualization',
            old_name='post_id',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='visualization',
            old_name='user_id',
            new_name='user',
        ),
    ]
