name: Deploy Django to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write   # OIDC obrigatório

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Login sem chave (OIDC)
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      # Docker Auth
      - name: Configure Docker
        run: |
          gcloud auth configure-docker ${{ secrets.GCP_REGION }}-docker.pkg.dev

      # Build + Push
      - name: Build and Push Docker Image
        run: |
          IMAGE=${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/django-repo/django-app

          docker build -t $IMAGE .

          docker push $IMAGE

      # Deploy Cloud Run
      - name: Deploy to Cloud Run
        run: |
          IMAGE=${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/django-repo/django-app

          gcloud run deploy django-service \
            --image $IMAGE \
            --region ${{ secrets.GCP_REGION }} \
            --platform managed \
            --allow-unauthenticated \
            --add-cloudsql-instances ${{ secrets.CLOUDSQL_CONNECTION_NAME }} \
            --set-env-vars \
              SECRET_KEY=${{ secrets.SECRET_KEY }},\
              MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }},\
              MYSQL_USER=${{ secrets.MYSQL_USER }},\
              MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}
